#class_name BrewerySignals (Autoload)
extends Node

@warning_ignore("unused_signal")
signal brewery_state_changed(brewery: Brewery)
@warning_ignore("unused_signal")
signal dialogue_pushed(text: String, is_special: bool, slot_index: int, character_global_pos: Vector2, display_time: float, fade_time: float)
@warning_ignore("unused_signal")
signal style_discovered(style: int)
@warning_ignore("unused_signal")
signal avi_raid_triggered(confiscated_bottles: int, fine_amount: int, reputation_lost: int)
@warning_ignore("unused_signal")
signal recipe_saved(recipe_name: String)
@warning_ignore("unused_signal")
signal bottles_sold(amount: int)
@warning_ignore("unused_signal")
signal recipe_save_rejected()