extends Node

const PATH_TO_INGREDIENTS : String = "res://src/resources/ingredients/"
const PATH_TO_BREW_STYLES : String = "res://src/resources/beer_styles/"

const TUNTEMATON : String = "Tuntematon"
const KOTIKALJA : String = "Kotikalja"
const BULKKILAGER : String = "Bulkkilager"
const TUMMALAGER : String = "Tumma Lager"
const PALEALE : String = "Pale Ale"
const AMBERALE : String = "Amber Ale"
const IPA : String = "IPA"
const HELLES : String = "Helles"
const VIENNALAGER : String = "Vienna Lager"
const MARZEN : String = "Märzen"
const BALTICPORTTERI : String = "Baltic Portteri"
const DOPPELBOCK : String = "Doppelbock"
const HEFEWEIZEN : String = "Hefeweizen"
const WITBIER : String = "Witbier"
const SESSIONALE : String = "Session Ale"
const SAISON : String = "Saison"
const BELGIANDUBBEL : String = "Belgian Dubbel"
const BELGIANSTRONGDARK : String = "Belgian Strong Dark Ale"
const SCOTCHALE : String = "Scotch Ale"
const BARLEYWINE : String = "Barleywine"
const IMPERIALSTOUT : String = "Imperial Stout"
const ALKOHOLITONIPA : String = "Alkoholiton IPA"
const ALKOHOLITONLAGER : String = "Alkoholiton Lager"
const SAHTI : String = "Sahti"
const MAITOSTOUT : String = "Maitostout"

const KG : String = "kg"
const G : String = "g"
const KPL : String = "kpl"
const SLASH : String = "/"
const RESOURCE_END : String = ".tres"

const MALT_STAT_STRING : String = "EBC: %s"
const HOP_STAT_STRING : String = "Alfahapot: %s%% / Beetahapot: %s%%"
const YEAST_STAT_STRING : String = "Käymisaste: %s%%"
const INGREDIENT_LABEL_WITH_STAT_STRING : String = "%s: %s %s (%s)"

const RECIPE_LIBRARY_TITLE : String = "Reseptikirja"
const RECIPE_LIBRARY_CLOSE_TEXT : String = "Sulje"

const COLOR_HINT_PALE : String = "vaalea"
const COLOR_HINT_GOLDEN : String = "kultainen"
const COLOR_HINT_AMBER : String = "meripihkan"
const COLOR_HINT_BROWN : String = "ruskea"
const COLOR_HINT_BLACK : String = "musta"

const BITTERNESS_HINT_MILD : String = "mieto"
const BITTERNESS_HINT_BALANCED : String = "tasapainoinen"
const BITTERNESS_HINT_BITTER : String = "karvas"
const BITTERNESS_HINT_VERY_BITTER : String = "erittäin karvas"

const INGREDIENT_LOCKED_LABEL : String = "??? – vaatii mainetta: %d"
const INGREDIENT_LOCKED_ERROR : String = "Ainesosa ERROR: %s vaatii vähintään %d mainetta"

const LEADERBOARD_BUTTON_TEXT : String = "Ennätykset"

const HOP_FLAVOR_STRING : String = "Maku: %s"
const HOP_FLAVOR_CITRUS : String = "Sitruksinen"
const HOP_FLAVOR_TROPICAL : String = "Trooppinen"
const HOP_FLAVOR_PINE : String = "Mäntyinen"
const HOP_FLAVOR_NOBLE : String = "Jalo"
const HOP_FLAVOR_EARTHY : String = "Maanläheinen"

const QUALITY_TIER_POOR : String = "Heikko"
const QUALITY_TIER_MEDIOCRE : String = "Tyydyttävä"
const QUALITY_TIER_GOOD : String = "Hyvä"
const QUALITY_TIER_EXCELLENT : String = "Erinomainen"
const QUALITY_TIER_MASTERFUL : String = "Mestarillinen"

const BREW_QUALITY_BREAKDOWN_TOOLTIP : String = "Osumatarkkuus: %s%%\nHumalalajeja käytetty: %s\nHumalatasapaino-bonus: %s%%\nMakuosuma: %s\nMaustebonus: %s%%"
const YES_STRING : String = "Kyllä"
const NO_STRING : String = "Ei"

const DATABASE_STRING : String = "Database"
const LIST_STRING : String = "List"
const INVENTORY_STRING : String = "Inventory"
const MONEY_STRING : String = "Money"

const INVALID_ID_ERROR : String = "%s ERROR: item with ID: %s does not exist in %s"
const WITHDRAW_NO_STOCK_ERROR : String = "%s ERROR: withdraw failed. Not enough stock for: %s"
const WITHDRAW_INVALID_AMOUNT_ERROR : String = "%s ERROR: withdraw failed. Invalid withdraw amount: %s"
const RESOURCE_ERROR : String = "Resource ERROR: currently have %s, and need %s %s"
const TABLE_EMPTY_ERROR : String = "Start Brewing ERROR: table has no ingredients"
const NOT_ENOUGH_INGREDIENTS_ERROR : String = "Brew resolver ERROR: not enough ingredients"
const DATABASE_DUBLICATE_KEY_ERROR : String = "ERROR: ID %s is already in use! Dublicate key: %s"
const INVALID_EXPORT_SCRIPT_ERROR : String = "%s ERROR: Export script is null"
const TYPE_ERROR : String = "ERROR: ID %s is correct type, but file is not correct inherited class!"
const INVALID_ADD_AMOUNT_ERROR : String = "%s ERROR: Trying to add %s amount of ingredient with ID: %s"

const FOLDER_SCAN_MESSAGE : String = "[IngredientDatabase] Start recursive folder scan..."
const FOLDER_SCAN_COMPLETE_MESSAGE : String = "[IngredientDatabase] Database fully sorted! Total registered items: "

const LVV_RAID_TITLE : String = "LVV-TARKASTUS!"
const LVV_RAID_MESSAGE : String = "Alkoholitarkastajat ryntäsivät kellariin ja takavarikoivat %s annosta valmista olutta! Lisäksi kirjoittivat sakon: %.1f €, ja maineesi laski %s pistettä."
const LVV_RAID_CLOSE_TEXT : String = "Selvä..."

## RunPerk.get_stat_summary() lines — only the non-neutral fields are ever
## shown (see that function), so every perk's numbers are always positive.
const PERK_QUALITY_STAT_STRING : String = "Laatu: %s"
const PERK_REPUTATION_STAT_STRING : String = "Maineen kertymä: %s"
const PERK_TIP_STAT_STRING : String = "Tipit: %s"
const PERK_DISTRIBUTION_STAT_STRING : String = "Jakelutulot: %s"
const PERK_YIELD_STAT_STRING : String = "Pullosaanto: %s"
const PERK_REFUND_CHANCE_STAT_STRING : String = "Ainepalautuksen mahdollisuus: %s"
const PERK_PEAK_SPEED_STAT_STRING : String = "Kypsymisaika: %s"
const PERK_DECLINE_RATE_STAT_STRING : String = "Heikkeneminen: %s"
const PERK_SPAWN_INTERVAL_STAT_STRING : String = "Asiakkaiden saapumisväli: %s"
const PERK_WALK_IN_COMPANY_CHANCE_STAT_STRING : String = "Asiakas tuo seuraa: %s"
const PERK_WALK_IN_COMPANY_BONUS_STAT_STRING : String = "Seurueessa asiakkaita: %s"
const PERK_AGENTTI_APPEARANCE_STAT_STRING : String = "Agenttien esiintyvyys: %s"
const PERK_MAFIOSO_APPEARANCE_STAT_STRING : String = "Mafiosojen esiintyvyys: %s"
const PERK_COUNTER_PRICE_STAT_STRING : String = "Tiskimyynnin hinnat: %s"
const PERK_GROUP_EVENT_INTERVAL_STAT_STRING : String = "Ryhmäasiakkaiden saapumisväli: %s"
const PERK_EXTRA_RAID_STRIKES_STAT_STRING : String = "Ratsioiden sietokyky: %s"
const PERK_RAID_HIDDEN_BATCH_STAT_STRING : String = "Piilotettuja eriä ratsiassa: %s"
const PERK_RAID_SAVED_BOTTLE_SHARE_STAT_STRING : String = "Ratsiassa säästyviä pulloja: %s"
const PERK_EXTRA_COUNTER_SLOTS_STAT_STRING : String = "Lisää tiskipaikkoja: %s"
const PERK_EXTRA_DAILY_GOAL_ROLLS_STAT_STRING : String = "Päivätavoitteita päivässä: %s"
const PERK_TIP_DOUBLE_CHANCE_STAT_STRING : String = "Mahdollisuus tuplatippiin: %s"
const PERK_BAR_FIGHT_CHANCE_STAT_STRING : String = "Tappelun todennäköisyys: %s"
## Explains PerkStats.value_text() wherever perk values are listed.
const PERK_VALUE_LEGEND : String = "+ % lasketaan yhteen, × kertoo kokonaisuuden."

## RunPerk.get_tier_label() — shown on LevelUpWindow's cards (color-coded
## via RunPerk.get_tier_color()) so a level-up's rarity is actually visible
## instead of every perk offer looking the same.
const PERK_TIER_COMMON : String = "Tavallinen"
const PERK_TIER_RARE : String = "Harvinainen"
const PERK_TIER_LEGENDARY : String = "Legendaarinen"

## RunPerk.get_stat_summary() lines, signed (%+d) since a perk can push either way.
const PERK_RAID_THRESHOLD_STAT_STRING : String = "Ratsiakynnys: %s"
const PERK_INGREDIENT_PRICE_STAT_STRING : String = "Ainehinnat: %s"

const RUN_EFFECTS_TITLE : String = "Kauden tilastot"
const RUN_EFFECTS_CLOSE_TEXT : String = "Sulje"
const RUN_EFFECTS_RAID_THRESHOLD_STRING : String = "Ratsiakynnys tällä kaudella: %d riskiä"
const RUN_EFFECTS_PERKS_HEADER : String = "Tämän kauden perkit (%d):"
const RUN_EFFECTS_NO_PERKS_STRING : String = "Ei vielä perkkejä. Nouse tasolle 2 saadaksesi ensimmäisen."
const RUN_EFFECTS_PERK_ROW_FORMAT : String = "%s %s%s"
const RUN_EFFECTS_PERK_ROW_COUNT_SUFFIX : String = " ×%d"
const RUN_EFFECTS_TOTALS_HEADER : String = "Yhteisvaikutus:"
const RUN_EFFECTS_TOTALS_QUALITY : String = "Laatubonus jokaiseen erään: +%d %%"
const RUN_EFFECTS_TOTALS_REPUTATION : String = "Maineen kertymä: +%d %%"
const RUN_EFFECTS_TOTALS_TIP : String = "Tipit: +%d %%"
